version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: previsit-postgres
    restart: unless-stopped
    environment:
      GROQ_API_KEY:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: previsit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: previsit-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      GROQ_API_KEY:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/previsit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres_data: